// Generated by https://quicktype.io

export interface JugadorInfo {
  jugador: JugadorInfo2;
  partidos: number;
  goles: number;
  asistencias: number;
  tarjetasAmarillas: number;
  tarjetasRojas: number;
}

interface JugadorInfo2 {
  id: number;
  sueldo: number;
  cargo: null;
  posicion: string;
  fecha_nacimiento: string;
  equipo_anterior: string;
  createdAt: string;
  updatedAt: string;
  usuarioId: number;
  equipoId: number;
  usuario: Usuario;
  equipo: Equipo;
}

interface Equipo {
  id: number;
  nombre: string;
  tipo: string;
  escudo: string;
  categoriaId: number;
}

interface Usuario {
  id: number;
  nombre: string;
  apellido: string;
  rut: string;
  email: string;
  clave: string;
  telefono: number;
  fotografia: string;
  fecha_incorporacion: string;
  nacionalidad: string;
}
